#!/bin/sh
#
# @title postcpbackup
# ------------------------------------------------------------------------------------------
# @author Brian Coogan
# @company WhiteDogGreenFrog
# @date Sept 2008
# @source http://whmscripts.net/backups/2010/postcpbackup-auto-cpbackup-rotation/
# ------------------------------------------------------------------------------------------
# @author Myles McNamara
# @date 05/22/2013
# @version 1.5
# @source http://gh.smyl.es/postcpbackup
# @description This script is used to automate cPanel backup rotation.
# ------------------------------------------------------------------------------------------
# @usage Save file to /scripts/postcpbackup, configure backups in WHM, check postcpbackup in "Execute Pre/Post Backup Script".
# @test run "test=echo /scripts/postcpbackup" to echo out what the script will do.
# ------------------------------------------------------------------------------------------
# @copyright Copyright (C) 2013  Myles McNamara
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------------------

# number of each backup to keep... comment out to skip that rotation
keepmonthly=2
keepweekly=3
keepdaily=7

# modify the settings below to control nice and ionice
# for nice, accepted values are -20 through 19, with 19 being the lowest priority.
nicecd=19

# for ionice, scheduling class accepted values are 1 (realtime), 2 (best-effort), 3 (idle)
ionicesc=2

# for ionice, class data accepted values are 0-7, 7 being the lowest priority.
ionicecd=7

# comment out line below if you do not want to use nice or ionice
nice='/bin/nice -n $nicecd /usr/bin/ionice -c$ionicesc -n$ionicecd'

# that's all folks.

export PATH=$PATH:/usr/local/sbin:/usr/local/bin
export POSTCPBACKUP=$$

if testing=echo system.backup 2>/dev/null 1>&2
then
   # backup system directories with optional script
   system.backup
fi


$debug cd /backup/cpbackup || exit 1
test -s .postcpbackup && . .postcpbackup

# daily backup - if daily is new, archive it and rotate archives
if [ "$keepdaily" != "" -a -d daily/files ]
then
    (( keepdaily++ ))
    cdate=$(date +"%Y%m%d")
    $test $nice mv daily daily_$cdate
    $test mkdir daily
    ls -d daily?* 2>/dev/null | tac | tail -n +$keepdaily |
	xargs -r $test $nice rm -rf 2>/dev/null
fi

# if the weekly backup is new, archive it and rotate archives
if [ "$keepweekly" != "" -a -d weekly/files ]
then
    (( keepweekly++ ))
    cdate=$(date +"%Y%m%d")
    $test $nice mv weekly weekly_$cdate
    $test mkdir weekly
    ls -d weekly?* 2>/dev/null | tac | tail -n +$keepweekly |
	xargs -r $test $nice rm -rf 2>/dev/null
fi

# if the monthly backup is new, archive it and rotate archives
if [ "$keepmonthly" != "" -a -d monthly/files ]
then
    (( keepmonthly++ ))
    cdate=$(date +"%Y%m")
    $test $nice mv monthly monthly_$cdate
    $test mkdir monthly
    ls -d monthly?* 2>/dev/null | tac | tail -n +$keepmonthly |
	xargs -r $test $nice rm -fr 2>/dev/null
fi

exit 0

# -end-
